import assert from 'node:assert/strict';
import fs from 'node:fs';
import {registerHooks} from 'node:module';
registerHooks({resolve(spec,context,next){if(spec==='three')return {url:new URL('../public/vendor/three.module.min.js',import.meta.url).href,shortCircuit:true};return next(spec,context);}});
const {classicSculpture:questModel}=await import('../public/classic-sculptures.mjs');
const {classicFixtures}=await import('./classic-fixtures.mjs');
const {ALL_IDS,ISLAND2_IDS,ISLAND2_SPAWNS,createState,newPokemon,hpMax,evolve,evolutionOptions,walkable}=await import('../public/data.mjs');
const {validateSnapshot}=await import('../public/save-format.mjs');
const {resolveTurn}=await import('../public/battle.mjs');
let checks=0;const check=(condition,label)=>{assert.ok(condition,label);checks++;};
check(ALL_IDS.length===31&&ISLAND2_IDS.length===19,'All species from photograph and boss are present');
for(const id of ALL_IDS){const m=questModel(id),g=m.geometry;check(g.attributes.position.count>=24*15,`Detailed rounded geometry ${id}`);check(g.attributes.color.count===g.attributes.position.count,`Vertex colours ${id}`);g.computeBoundingBox();check(g.boundingBox.max.y>g.boundingBox.min.y,`Nonzero model height ${id}`);for(const v of g.attributes.position.array)assert.ok(Number.isFinite(v));}
for(const spawn of ISLAND2_SPAWNS)check(walkable(spawn.x,spawn.z),`Reachable encounter ${spawn.id}`);
for(const [id,next,level] of [[74,75,25],[75,76,36],[54,55,33],[116,117,32],[118,119,33],[60,61,25],[86,87,34]]){const s=createState(),p=newPokemon(id,level-1);check(!evolve(p,s,next),'Level gate');p.level=level;check(evolve(p,s,next),'Second island evolution');}
check(evolutionOptions(newPokemon(129,50),createState()).length===0,'Magikarp never evolves');
const stoneState=createState();stoneState.stones.water=1;check(evolve(newPokemon(61),stoneState,62)&&stoneState.stones.water===0,'Poliwhirl water stone consumed');
function fixture(island=1){const s=createState();s.started=true;s.island=island;s.candies=3;s.party=[newPokemon(25,40),newPokemon(7,30)];s.caught=new Set([25,7]);s.seen=new Set([25,7]);return {version:3,state:{...s,seen:[...s.seen],caught:[...s.caught],visited:[],pickedStones:[]},regions:{},world:{position:[0,18],rotation:0,yaw:0,pitch:.52,distance:12,playedSeconds:5,wild:Array.from({length:island===2?20:15},(_,key)=>({key,id:island===2?ISLAND2_SPAWNS[key].id:25,visible:true,nextChangeAt:0,x:0,z:0,phase:0})),pickups:Array.from({length:13},(_,key)=>({key,readyAt:0}))},battle:null,settings:{soundEnabled:false}};}
const old=fixture();old.version=2;delete old.state.island;delete old.state.island2Wins;delete old.state.bossDefeated;delete old.regions;const migrated=validateSnapshot(old);check(migrated.version===3&&migrated.state.island===1,'Legacy save migrates to island 1');check(migrated.state.party[0].uid===old.state.party[0].uid&&migrated.state.balls===old.state.balls,'Legacy party and inventory retained');
const two=fixture(2);two.regions[1]=old.world;two.state.bossDefeated=true;const round=validateSnapshot(two);check(round.regions[1].wild.length===15&&round.world.wild.length===20&&round.state.bossDefeated,'Both island states survive validation');
const state=createState();state.started=true;state.candies=0;state.party=[newPokemon(25,40),newPokemon(7,40)];const battle={own:state.party[0],enemy:newPokemon(54,20),turn:0,specialCooldown:0,wild:{boss:false}};
const before=state.party[1].hp;let result=resolveTurn(state,battle,{type:'switch',index:1},()=>.99);check(!result.result&&battle.own===state.party[1]&&state.active===1&&battle.turn===1&&battle.own.hp<before,'Switch costs a turn and incoming ally is hit');const turn=battle.turn;check(resolveTurn(state,battle,{type:'switch',index:1}).error&&battle.turn===turn,'Invalid switch consumes no turn');
battle.own.hp=1;result=resolveTurn(state,battle,'attack',()=>.99);check(result.result!=='defeat'&&battle.own===state.party[0]&&state.active===0,'Fainted ally is replaced without losing battle');
const bossState=createState();bossState.island=2;bossState.candies=0;bossState.party=[newPokemon(25,50)];const boss={own:bossState.party[0],enemy:newPokemon(55,45),turn:0,specialCooldown:0,wild:{boss:true}};check(resolveTurn(bossState,boss,'catch').error,'Boss cannot be captured');boss.enemy.hp=1;result=resolveTurn(bossState,boss,'attack',()=>.99);check(result.result==='victory'&&bossState.bossDefeated&&bossState.candies===5&&bossState.island2Wins===1,'Boss reward and completion stored once');check(resolveTurn(bossState,boss,'attack').error&&bossState.candies===5,'Resolved boss never grants reward twice');
two.state.party=state.party;two.state.active=state.active;two.state.caught=[25,7];two.state.seen=[25,7];two.battle={wildKey:3,enemy:newPokemon(54,20),ownUid:state.party[state.active].uid,turn:2,specialCooldown:0};check(validateSnapshot(two).battle.ownUid===battle.own.uid,'Save after forced switch restores correct fighter');
const manifest=JSON.parse(fs.readFileSync('public/manifest.webmanifest'));check(manifest.orientation==='any'&&manifest.display==='standalone','Both orientations in install manifest');for(const icon of manifest.icons)check(fs.existsSync('public'+icon.src),'Install icon exists');
console.log(`PASS: ${checks} second-island, rounded-model, migration, switch, boss and installation checks`);
// Exercise actual island construction and restore without a GPU renderer.
const THREE=await import('../public/vendor/three.module.min.js');
globalThis.document={createElement:()=>({width:0,height:0,getContext:()=>({fillText(){}})})};
const {World}=await import('../public/world.mjs');const world=Object.create(World.prototype);
Object.assign(world,{shadowTexture:null,island:1,layouts:{},bossDefeated:false,scene:new THREE.Scene(),environment:new THREE.Group(),models:await classicFixtures(),pickups:[],obstacles:[],wild:[],clock:0,cameraMode:'explore',playerPos:new THREE.Vector3(0,0,18),trainer:new THREE.Group(),cameraYaw:0,cameraPitch:.52,cameraDistance:12});world.scene.background=new THREE.Color();world.scene.fog=new THREE.Fog(0xffffff,10,100);world.buildTerrain();world.buildNature();world.buildCamp();world.buildPickups();world.buildAtmosphere();world.scene.add(world.environment);world.spawnWild();const firstWorld=world.snapshotWorld();world.configureIsland(2);assert.equal(world.wild.length,20);assert.equal(world.wild[19].id,55);world.wild[19].visible=false;world.wild[19].group.visible=false;world.bossDefeated=true;const secondWorld=world.snapshotWorld();world.configureIsland(1);world.restoreWorld(firstWorld);assert.deepEqual(world.snapshotWorld().position,firstWorld.position);world.configureIsland(2);world.restoreWorld(secondWorld);assert.equal(world.wild[19].visible,false);assert.equal(world.pickups.length,13);console.log('PASS: Actual scene construction, island round-trip and defeated boss restoration');
const {createApp}=await import('../server/index.mjs');const {mkdtemp,rm}=await import('node:fs/promises');const {tmpdir}=await import('node:os');const dir=await mkdtemp(tmpdir()+'/pokeblox-islands-');let app;
try{const start=async()=>{app=await createApp({dbPath:dir+'/game.db',production:false,backups:false});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));return 'http://127.0.0.1:'+app.server.address().port;};let base=await start();const registration=await fetch(base+'/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'island_tester',password:'local-test-only-phrase'})});assert.equal(registration.status,201);const cookie=registration.headers.get('set-cookie').split(';')[0],auth=await registration.json();const write=async(snapshot,revision,writeId)=>fetch(base+'/api/save',{method:'POST',headers:{'Content-Type':'application/json',cookie,'X-CSRF-Token':auth.csrfToken},body:JSON.stringify({snapshot,revision,writeId})});assert.equal((await write(old,0,'migrate-v2-local')).status,200);assert.equal((await write(two,1,'island-2-local')).status,200);await app.close();app=null;base=await start();const restored=await (await fetch(base+'/api/save',{headers:{cookie}})).json();assert.equal(restored.snapshot.state.island,2);assert.equal(restored.snapshot.state.bossDefeated,true);assert.equal(restored.snapshot.regions[1].wild.length,15);assert.equal(restored.snapshot.battle.ownUid,two.battle.ownUid);assert.equal((await write(old,2,'old-client-local')).status,409);console.log('PASS: v2 migration, island-2 battle and boss persist after real server restart; old-client downgrade blocked');}finally{if(app)await app.close();await rm(dir,{recursive:true,force:true});}
