import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApp} from '../server/index.mjs';
import {BASES,ALL_IDS,STARTER_ID,baseStats,createState,newPokemon,reserveUids,hpMax,catchChance,rollEncounter,ENCOUNTERS} from '../public/data.mjs';
import {SaveClient} from '../public/saving.mjs';
import {resolveTurn} from '../public/battle.mjs';
import {validateSnapshot} from '../public/save-format.mjs';
let count=0;const check=(value,message)=>{assert.ok(value,message);count++;};
const fixture=()=>{const s=createState();s.candies=3;s.started=true;s.party=[newPokemon(25,5)];s.caught.add(25);s.seen.add(25);return {version:2,state:{...s,seen:[...s.seen],caught:[...s.caught],pickedStones:[],visited:[]},world:{position:[0,18],rotation:0,yaw:0,pitch:.52,distance:12,playedSeconds:4,wild:Array.from({length:15},(_,key)=>({key,id:BASES[key%BASES.length],visible:true,nextChangeAt:Date.now()+80000,x:0,z:0,phase:0})),pickups:Array.from({length:13},(_,key)=>({key,readyAt:0}))},battle:null,settings:{soundEnabled:false}};};
check(STARTER_ID===25,'Pikachu is the sole starter');check(baseStats(6).total===534&&ALL_IDS.every(id=>baseStats(id).total<=534),'Charizard has the highest researched base-stat total');check(baseStats(25).captureRate===190&&baseStats(133).captureRate===45,'Source catch coefficients');for(const [zone,entries]of Object.entries(ENCOUNTERS))check(entries.reduce((a,b)=>a+b[1],0)===100,'Each zone probability totals 100%');check(rollEncounter('meadow',()=>.96)===133,'Eevee occupies the final five percent');check(rollEncounter('rocks',()=>.994)===25&&rollEncounter('rocks',()=>.999)===6,'Charizard occupies the final half percent');
const p=newPokemon(25,5),eevee=newPokemon(133,5);check(catchChance(p)>catchChance(eevee),'Pikachu is easier to catch at full health');reserveUids([{uid:900}]);check(newPokemon(25).uid>900,'Restored IDs do not collide');
const progress=createState();progress.candies=2;progress.started=true;progress.party=[newPokemon(25,5)];progress.caught.add(25);progress.seen.add(25);const enemy=newPokemon(133,5);enemy.hp=1;const encounter={own:progress.party[0],enemy,turn:0,specialCooldown:0};const result=resolveTurn(progress,encounter,'catch',()=>0);check(result.result==='catch'&&progress.party.length===2&&progress.balls===19,'Capture commits a full consistent result before animations');const countBefore=progress.party.length;check(resolveTurn(progress,encounter,'catch',()=>0).error&&progress.party.length===countBefore,'Resolved turn cannot award twice');
const data=fixture();check(validateSnapshot(data).state.party[0].species===25,'Valid full snapshot');assert.throws(()=>validateSnapshot({...data,world:{...data.world,position:[35,4]}}));count++;const dir=await mkdtemp(join(tmpdir(),'pokeblox-test-')),dbPath=join(dir,'progress.db');let app,base;
async function start(){app=await createApp({dbPath,backups:false});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${app.server.address().port}`;}
async function request(path,{method='GET',body,cookie,csrf,origin}={}){const headers={};if(body)headers['Content-Type']='application/json';if(cookie)headers.Cookie=cookie;if(csrf)headers['X-CSRF-Token']=csrf;if(origin)headers.Origin=origin;const r=await fetch(base+path,{method,headers,body:body?JSON.stringify(body):undefined});const text=await r.text();let json;try{json=JSON.parse(text);}catch{}return {status:r.status,json,headers:r.headers,text};}
try{
 await start();check((await request('/healthz')).status===200,'Server starts');check((await request('/')).status===200,'Public game HTML');check((await request('/assets/25.glb')).headers.get('content-type')==='model/gltf-binary','3D model served');check((await request('/api/save')).status===401,'Save requires an account');check((await request('/api/me')).json.user===null,'Anonymous visitors are not silently assigned an account');
 const a=await request('/api/register',{method:'POST',body:{username:'Trainer_A',password:'secure-test-phrase-1'}});check(a.status===201,'Register first account');const cookieA=a.headers.get('set-cookie').split(';')[0],csrfA=a.json.csrfToken;check(a.headers.get('set-cookie').includes('HttpOnly')&&a.headers.get('set-cookie').includes('SameSite=Lax'),'Protected session cookie');
 const b=await request('/api/register',{method:'POST',body:{username:'Trainer_B',password:'secure-test-phrase-2'}});check(b.status===201,'Register second account');const cookieB=b.headers.get('set-cookie').split(';')[0];check((await request('/api/register',{method:'POST',body:{username:'trainer_a',password:'secure-test-phrase-3'}})).status===409,'Case insensitive unique username');check((await request('/api/login',{method:'POST',body:{username:'Trainer_A',password:'wrong-passphrase'}})).status===401,'Wrong password rejected');check((await request('/api/me',{cookie:cookieA})).json.user.username==='Trainer_A','Session recognizes its player');
 const write={revision:0,writeId:'test-write-0001',snapshot:data};check((await request('/api/save',{method:'POST',cookie:cookieA,body:write})).status===403,'CSRF required');check((await request('/api/save',{method:'POST',cookie:cookieA,csrf:csrfA,origin:'https://other.example',body:write})).status===403,'Cross-origin mutation rejected');const saved=await request('/api/save',{method:'POST',cookie:cookieA,csrf:csrfA,body:write});check(saved.status===200&&saved.json.revision===1,'Progress stored');check((await request('/api/save',{cookie:cookieB})).json.snapshot===null,'Different player cannot see another save');const dup=await request('/api/save',{method:'POST',cookie:cookieA,csrf:csrfA,body:write});check(dup.status===200&&dup.json.revision===1,'Retries are idempotent');check((await request('/api/save',{method:'POST',cookie:cookieA,csrf:csrfA,body:{...write,writeId:'stale-write-0002'}})).status===409,'Stale tab cannot overwrite newer save');const bad=structuredClone(data);bad.state.party[0].species=9999;check((await request('/api/save',{method:'POST',cookie:cookieA,csrf:csrfA,body:{revision:1,writeId:'invalid-save-001',snapshot:bad}})).status===400,'Malformed progress rejected without overwriting');
 const before=app.db.prepare('SELECT password_hash FROM users WHERE username_key = ?').get('trainer_a');check(before.password_hash.startsWith('scrypt32768$')&&!before.password_hash.includes('secure-test'),'Password hash only');await app.close();await start();const restored=await request('/api/save',{cookie:cookieA});check(restored.status===200&&restored.json.revision===1&&restored.json.snapshot.state.party[0].species===25,'Full progress and login survive actual server restart');check(JSON.stringify(restored.json.snapshot)===JSON.stringify(validateSnapshot(data)),'Saved world, inventory, settings and quests round-trip exactly');const battleData=structuredClone(data);battleData.battle={wildKey:0,enemy:newPokemon(BASES[0],5),ownUid:battleData.state.party[0].uid,turn:3,specialCooldown:1};check((await request('/api/save',{method:'POST',cookie:cookieA,csrf:csrfA,body:{revision:1,writeId:'battle-save-0002',snapshot:battleData}})).status===200,'Battle turn saved');const continued=(await request('/api/save',{cookie:cookieA})).json.snapshot;check(continued.battle.turn===3&&continued.battle.specialCooldown===1,'Battle resumes on same completed turn');check((await request('/api/logout',{method:'POST',cookie:cookieA,csrf:csrfA})).status===200,'Logout works');check((await request('/api/save',{cookie:cookieA})).status===401,'Logged-out session is revoked');const login=await request('/api/login',{method:'POST',body:{username:'trainer_a',password:'secure-test-phrase-1'}});check(login.status===200,'Re-login after restart');const again=(await request('/api/save',{cookie:login.headers.get('set-cookie').split(';')[0]})).json;check(again.revision===2&&again.snapshot.battle.turn===3,'Same account recovers its saved battle');

 const c=await request('/api/register',{method:'POST',body:{username:'Trainer_C',password:'secure-test-phrase-3'}}),cookieC=c.headers.get('set-cookie').split(';')[0],originalFetch=globalThis.fetch,drafts=new Map();let loseAck=false;const clients=[];
 function client(){const statuses=[],value=new SaveClient({csrfToken:c.json.csrfToken},status=>statuses.push(status));value.draft=async(action,entry,key=value.accountKey)=>{if(action==='get')return structuredClone(drafts.get(key)??null);if(action==='put')drafts.set(key,structuredClone(entry));if(action==='delete')drafts.delete(key);return null;};value.statuses=statuses;clients.push(value);return value;}
 globalThis.fetch=async(url,options={})=>{const response=await originalFetch(new URL(url,base),{...options,headers:{...options.headers,Cookie:cookieC}});if(loseAck&&options.method==='POST'){loseAck=false;await response.text();throw Error('Connection lost after commit');}return response;};
 try{
  const first=client();check(await first.load()===null,'Client loads new account');first.enqueue(data);loseAck=true;check(!await first.flush(),'Lost acknowledgement is reported as unsent');const newer=structuredClone(data);newer.state.balls=18;first.enqueue(newer);check(await first.flushAll()&&!first.blocked,'New progress recovers an uncertain prior write without a false conflict');const cloud=await (await globalThis.fetch('/api/save')).json();check(cloud.revision===2&&cloud.snapshot.state.balls===18,'Latest client progress reaches server after lost acknowledgement');
  const second=client();const loaded=await second.load();check(loaded.state.balls===18,'New client restores cloud progress');first.enqueue({...newer,state:{...newer.state,balls:17}});await first.flushAll();second.enqueue({...newer,state:{...newer.state,balls:16}});check(!await second.flushAll()&&second.blocked&&second.statuses.includes('conflict'),'A genuinely stale second client is blocked');
  const current=client();await current.load();current.enqueue({...newer,state:{...newer.state,balls:15}});loseAck=true;await current.flush();const restoredClient=client();const restoredDraft=await restoredClient.load();check(restoredDraft.state.balls===15&&!restoredClient.pending,'Reload after acknowledgement loss recognizes the already saved draft');
 }finally{globalThis.fetch=originalFetch;for(const client of clients){client.blocked=true;clearTimeout(client.timer);}}
 console.log(`PASS: ${count} account, client synchronization, persistence, rarity, capture, conflict and restart checks.`);
}finally{if(app)await app.close();await rm(dir,{recursive:true,force:true});}
